export default [
  {icon: "🍕", name: "Pizza"},
  {icon: "🍔", name: "Burger"},
  {icon: "🍟", name: "Chips"},
  {icon: "🌭", name: "Hotdog"},
  {icon: "🍿", name: "Popcorn"},
  {icon: "🧂", name: "Salt"},
  {icon: "🥓", name: "Bacon"},
  {icon: "🥚", name: "Egg"},
  {icon: "🍳", name: "Cooking"},
  {icon: "🧇", name: "Waffle"},
  {icon: "🥞", name: "Pancakes"},
  {icon: "🧈", name: "Butter"},
  {icon: "🍞", name: "Bread"},
  {icon: "🥐", name: "Croissant"},
  {icon: "🥨", name: "Pretzel"},
  {icon: "🥯", name: "Bagel"},
  {icon: "🥖", name: "Baguette"},
  {icon: "🧀", name: "Cheese"},
  {icon: "🥗", name: "Salad"},
  {icon: "🥙", name: "Stuffed Flatbread"},
  {icon: "🥪", name: "Sandwich"},
  {icon: "🌮", name: "Taco"},
  {icon: "🌯", name: "Burrito"},
  {icon: "🥫", name: "Can"},
  {icon: "🍖", name: "Meat on Bone"},
  {icon: "🍗", name: "Chicken Leg"},
  {icon: "🥩", name: "Steak"},
  {icon: "🍠", name: "Sweet Potato"},
  {icon: "🥟", name: "Dumping"},
  {icon: "🥠", name: "Fortune Cookie"},
  {icon: "🍘", name: "Rice Cracker"},
  {icon: "🍙", name: "Rice Ball"},
  {icon: "🍚", name: "Cooked Rice"},
  {icon: "🍛", name: "Curry Rice"},
  {icon: "🍜", name: "Noodles"},
  {icon: "🦪", name: "Oyster"},
  {icon: "🍣", name: "Sushi"},
  {icon: "🍤", name: "Prawn"},
  {icon: "🥧", name: "Pie"},
  {icon: "🍦", name: "Ice Cream Cone"},
  {icon: "🍧", name: "Shaved Ice"},
  {icon: "🍨", name: "Ice Cream"},
  {icon: "🍩", name: "Doughnut"},
  {icon: "🍪", name: "Cookie"},
  {icon: "🎂", name: "Cake"},
  {icon: "🍰", name: "Cake Slice"},
  {icon: "🧁", name: "Cupcake"},
  {icon: "🍫", name: "Choclate"},
  {icon: "🍬", name: "Sweet"},
  {icon: "🍭", name: "Lolly"},
  {icon: "🍮", name: "Egg Custard"},
  {icon: "🍯", name: "Honey Pot"},
  {icon: "🍼", name: "Baby Bottle"},
  {icon: "🥛", name: "Milk"},
  {icon: "🧃", name: "Juice"},
  {icon: "☕", name: "Coffee"},
  {icon: "🍵", name: "Green Tea"},
  {icon: "🍶", name: "Sake"},
  {icon: "🍾", name: "Champagne"},
  {icon: "🍷", name: "Wine"},
  {icon: "🍺", name: "Beer"},
  {icon: "🍻", name: "Cheers"},
  {icon: "🧊", name: "Ice Cube"},
  {icon: "🥝", name: "Kiwi"},
  {icon: "🥥", name: "Coconut"},
  {icon: "🍇", name: "Grapes"},
  {icon: "🍈", name: "Melon"},
  {icon: "🍉", name: "Watermelon"},
  {icon: "🍊", name: "Tangerine"},
  {icon: "🍋", name: "Lemon"},
  {icon: "🍌", name: "Banana"},
  {icon: "🍍", name: "Pineapple"},
  {icon: "🥭", name: "Mango"},
  {icon: "🍎", name: "Apple"},
  {icon: "🍐", name: "Pear"},
  {icon: "🍑", name: "Peach"},
  {icon: "🍒", name: "Cherry"},
  {icon: "🍓", name: "Strawberry"},
  {icon: "🍅", name: "Tomato"},
  {icon: "🍆", name: "Aubergine"},
  {icon: "🌽", name: "Corn"},
  {icon: "🌶", name: "Cherry"},
  {icon: "🍄", name: "Mushroom"},
  {icon: "🥑", name: "Avacado"},
  {icon: "🥒", name: "Cucumber"},
  {icon: "🥦", name: "Broccoli"},
  {icon: "🥔", name: "Potato"},
  {icon: "🧄", name: "Garlic"},
  {icon: "🧅", name: "Onion"},
  {icon: "🥕", name: "Carrot"},
  {icon: "🌰", name: "Chestnut"},
  {icon: "🥜", name: "Nut"},
];
